### ISSUE TITLE
Curriculum suggestions

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/curriculum#11]
Will use this to save a list of issues as we go through curriculum
- http://clojurebridge-berlin.github.io/curriculum/outline/simple_values.html#/4 "trinity" is a weird choice, doesn't mean much to people
- http://clojurebridge-berlin.github.io/curriculum/outline/simple_values.html#/15 (feet and inches don't mean much to people outside the US) 
- http://clojurebridge-berlin.github.io/curriculum/outline/data_structures.html#/5 having `first` turn up again in a different context is confusing (shows up as a keyword earlier) 
- http://clojurebridge-berlin.github.io/curriculum/outline/data_structures.html#/16 dead link, points to http://grimoire.arrdem.com/1.6.0/clojure.core/conj/ 
- http://clojurebridge-berlin.github.io/curriculum/outline/functions.html#/2  => give an example of the error case 
- http://clojurebridge-berlin.github.io/curriculum/outline/functions.html#/3 .... strange function... took us a long time to figure out what's going on

**Comment by Malwine** [comment]
- https://clojurebridge-berlin.github.io/curriculum/outline/simple_values.html#/10 Why prefix is **better**? Could we use something like: `benefits of prefix`

**Comment by vsmart** [comment]
- http://clojurebridge-berlin.github.io/curriculum/outline/data_structures.html#/12

Maybe change `update-in` to `update`. Works as well and is an easier signature. 

And maybe add a hint to explain the functional nature of the language: Update does not modify, it creates a new one. 
- http://clojurebridge-berlin.github.io/curriculum/outline/data_structures.html#/14 

`map` function has not been introduced yet, maybe add a hint there
- add more excitement, emoji

**Comment by Robsteranium** [comment]
PR #12 fixes a handful of these. I've got some other ideas to add. I thought I'd pop them into separate issues so it's easier to follow the discussion against each.

**Comment by Robsteranium** [comment]
I think all of the suggested listed above have either been patched or now have their own thread so it should be alright to close this issue.

**Comment by vsmart** [comment]
Sweet!!! 😍😍😍  Thank you @Robsteranium!
