### ISSUE TITLE
Remove `update-in`?

### ISSUE THREAD

**Issue by Robsteranium** [clojurebridge-berlin/curriculum#15]
As per #11, we should almost certainly be covering `update` before `update-in` (especially since we've not covered nested maps at this point). Moreover I wonder whether we should skip `update` at this early stage.

In our group this led inexorably into a discussion about immutability. That's clearly a crucial component of Clojure, but perhaps it doesn't need to be covered just yet?

It's also a higher-order function. Perhaps people ought to learn about functions themselves first?

**Comment by Robsteranium** [comment]
#24 replaces `update-in` with `update`. I suggest we leave it like that and see how it goes on Saturday.

**Comment by daveliepmann** [comment]
I am in favor of removing both `update` and `update-in`. I agree totally with "Perhaps people ought to learn about functions themselves first?" and "perhaps it doesn't need to be covered just yet?"

**Comment by Robsteranium** [comment]
Ok closing this one on `update-in`. See #34 for the discussion on `update`.
