### ISSUE TITLE
Description of Nightcode's REPL doesn't fit Nightcode 2.0.4

### ISSUE THREAD

**Issue by xamebax** [clojurebridge-berlin/curriculum#30]
The curriculum mentions that in Nightcode, the REPL always runs in the bottom left of the window. In Nightcode 2.0.4, the REPL is running in middle-right.

I might be doing something wrong, but that REPL isn't interactive if it's ran in the context of a project. The curriculum says:
> After this, you'll find a new REPL launch in that bottom pane. Here you
> can type commands just like the other REPL -- but now you can also type
> code in the main file, and run it with the `Eval` button
> (<kbd>ctrl</kbd>/<kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>x</kbd>, making sure the cursor is next to the code).

But I cannot type anything in that REPL. There is also no `Eval` button (only `Run` and `Run with REPL` and their behavior looks the same. It might be my lack of experience, but I don't understand the difference). The only way I can use the REPL properly is when I click on `Home` and then go to that window pane. I find this description confusing.

The text below is also not consistent with Nightcode 2.0.4, as there is now a `Start` button instead of a `New Project` button:
>* In NightCode, at the top left, click on "New Project"
>* Choose a location and a name (nb: don't call it `quil`)
>* Click on "Graphics" (the button with a big "Q" on it)

I am not creating a PR with changes since I am not a 100% sure the way Nightcode works on my Ubuntu Mate is how it will work on other OSs, so comments would be much appreciated.

**Comment by karlwestin** [comment]
Hey!
i was seeing this too as i was browsing through the curriculum before the workshop
in another place (http://clojurebridge-berlin.org/curriculum/outline/intro.html#/8) it says to use CMD/CTRL-E for eval, which also does not work

i know you said this curriculum is on its way out but would it be worth it if I make a PR to change this before the upcoming weekend anyway?

**Comment by daveliepmann** [comment]
A full pass on that slide would be a super-helpful PR, Karl. I see:

 - The old "New Project" -> "Graphics" process is now "Start" -> "Graphics Project"
 - As a novice Nightcoder, I see no way to evaluate lines 7 to 10 :/

**Comment by vsmart** [comment]
Hi @karlwestin @daveliepmann 
just a quick FYI -- we can and should use the latest version of the night code, 2.4.0 or at least 2.3 and up
At the last workshop we *had* to explicitly use an old version -- 2.0.4 -- because the creator of nightcode removed quil. After the workshop, we made an issue, and he re-added the quil feature. (read about it https://github.com/oakes/Nightcode/issues/208) 
so now we can jump back to the latest/newest versions.

**Comment by karlwestin** [comment]
@vsmart sounds great, thank you! just made a pr with instructions that i tested on 2.3.7 so i hope they're ok in 2.4 too
