### ISSUE TITLE
"Assignment"?

### ISSUE THREAD

**Issue by daveliepmann** [clojurebridge-berlin/curriculum#33]
In *outline/simple_values.md*, we use the word "Assignment" to describe `def`. This is not idiomatic Clojure terminology. Using this term

 1. confuses folks coming from other languages where "assignment" is a known but different concept
 2. teaches total newcomers words that are not common Clojure parlance

### Assignment means something else
In [Clojure reference material](https://clojure.org/reference/vars), "assignment" is reserved for atoms:

>### `(set! var-symbol expr)`
>Assignment special form.

### `def` isn't assignment
The [docs for `def`](https://clojuredocs.org/clojure.core/def) make no mention of "assignment" because the abstraction Clojure uses isn't *assignment* but *definition*.

### Clojurists don't say "assignment"
See for yourself: in a private browsing window, [search for "clojure assignment"](https://www.google.de/search?q=clojure+assignment). You'll get the `set!` snippet I just quoted, ClojureBridge materials, and an old Google Groups thread that is about the slippage in terminology between "assignment" in imperative languages and in Clojure.

## Conclusion
We should stop saying "assignment" entirely.

**Comment by Robsteranium** [comment]
sounds reasonable to me :+1:
