### ISSUE TITLE
`let` before `def`

### ISSUE THREAD

**Issue by daveliepmann** [clojurebridge-berlin/curriculum#35]
`let` should be introduced before `def` in *outline/functions.md*. It's more basic, it's smaller scale, it's more manageable/comprehensible, and it introduces *why* we use parens in lisps, as well as scope. (This is actually a broader problem with how `let` is introduced: no reason is given for using one rather than the other.)

**Comment by Robsteranium** [comment]
I'm inclined to agree. IIRC it ends-up being quite common to introduce `let` when building-up calculations in quil applications anyway.

It looks like `def` is first introduced in _outline/02_simple_values.md_. Perhaps `let` should used/ explained there instead?

We could even defer the introduction of `def` until after `defn` or simply ignore it...

**Comment by daveliepmann** [comment]
>IIRC it ends-up being quite common to introduce let when building-up calculations in quil applications

This sounds ideal for us.

>It looks like def is first introduced in outline/02_simple_values.md. Perhaps let should used/ explained there instead?

I will put together a PR.
